### ISSUE TITLE
Issue on calling callAPI() method.

### ISSUE THREAD

**Issue by uma075** [sunilbandla/msal-angular-sample#1]
Successfully logged in but when calling CallAPI method below error response generated after asking for login again.
Refused to display 'https://login.microsoftonline.com/te/xxxxxx.onmicrosoft.com/b2c_1_signinpolicy/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Fxxxxxxx.onmicrosoft.com%2Fuser.read%20openid%20profile&client_id=4275a27c-1088-4c8d-8add-c77231eaad24&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=XXXXX-XXXXX-XXXXX-XXXX-664122b4f481&nonce=a05b7788-e51b-447e-ae36-cd9547afe902&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.1.1&client-request-id=594f0328-fbaa-4ed1-9f74-ea3fc8e46284&prompt=none&domain_req=009a79ac-e497-491a-98d7-d7c48527de24&login_req=XXXXX-XXXXX-XXXXX-XXXX-664122b4f481-b2c_1_signinpolicy&domain_hint=organizations' **in a frame because it set 'X-Frame-Options' to 'deny'.**
msal.js:1707 GET https://login.microsoftonline.com/te/XXXXXX.onmicrosoft.com/b2c_1_signinpolicy/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2FXXXXX.onmicrosoft.com%2Fuser.read%20openid%20profile&client_id=XXXXX-XXXXX-XXXXX-XXXX-c77231eaad24&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=XXXXX-XXXXX-XXXXX-XXXX-664122b4f481&nonce=a05b7788-e51b-447e-ae36-cd9547afe902&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.1.1&client-request-id=594f0328-fbaa-4ed1-9f74-ea3fc8e46284&prompt=none&domain_req=009a79ac-e497-491a-98d7-d7c48527de24&login_req=a62a9d71-db82-4a93-9512-a37458dd79b2-b2c_1_signinpolicy&domain_hint=organizations net:**:ERR_BLOCKED_BY_RESPONSE**

**Comment by sunilbandla** [comment]
Could you post your question in the msal.js repo? That is the official repo and support is provided there.
