### ISSUE TITLE
Error 'User login is required' and app is getting redirected back to login page

### ISSUE THREAD

**Issue by SujitGodavarti** [sunilbandla/msal-angular-sample#3]
I am using MSAL in my angular app for authentication purpose. The error that is being thrown is "error getting accees token: user_login_error:User login is required" as shown in below image and the app gets redirected back to login page again. How can I successfully complete the login and get the token? 
I created a github repo for the code at 'https://github.com/SujitGodavarti/SamplePortalApp' with detailed instructions on how to run it mentioned in the ' README.md' file. 

![img3](https://user-images.githubusercontent.com/20764924/35373716-e17eb434-01f3-11e8-9037-0262c0830dc4.png)
Please help me solve this issue.

**Comment by sunilbandla** [comment]
The SDK authors will be able to help you better.
