### ISSUE TITLE
Not Able to resolve MSAL in Auth Service

### ISSUE THREAD

**Issue by vimitdhawan** [sunilbandla/msal-angular-sample#4]
I am not able resolve msal object in auth service

**Comment by nybroe** [comment]
Pin all packages in package.json, delete node_modules, do a "npm install" and it compiles

**Comment by sunilbandla** [comment]
Thanks @nybroe. If that worked, would it be possible for you to send a PR? Thanks!

**Comment by nybroe** [comment]
Please review:
https://github.com/sunilbandla/msal-angular-sample/pull/5
